
# Ejercicio final: Extraer información de un archivo JSON usando expresiones regulares (regex)


## Objetivo:

El objetivo de este ejercicio es practicar la utilización de expresiones regulares (regex) para extraer información específica de un archivo JSON. El ejercicio se enfocará en la lectura y análisis de un archivo JSON que contiene información sobre clientes.

## Descripción:

### Obtener el archivo JSON:
Lea archivo JSON 'clientes.json' que contiene la información sobre clientes. El archivo debe tener una estructura similar a la siguiente:

In [14]:
{
  "clientes": [
    {
      "nombre": "Juan Pérez",
      "direccion": "Calle Mayor 123",
      "ciudad": "San José",
      "telefono": "+506 2222-3333"
    },
    {
      "nombre": "María Gómez",
      "direccion": "Avenida Central 456",
      "ciudad": "Alajuela",
      "telefono": "+506 8888-4444"
    },
    {
      "nombre": "Pedro Ramírez",
      "direccion": "Barrio Escalante 789",
      "ciudad": "Heredia",
      "telefono": "+506 5555-6666"
    },
    {
      "nombre": "Ana Castro",
      "direccion": "Avenida 10 Calle 5",
      "ciudad": "Cartago",
      "telefono": "+506 3333-4444"
    },
    {
      "nombre": "Carlos Jiménez",
      "direccion": "Calle Principal 12",
      "ciudad": "Liberia",
      "telefono": "+506 6666-7777"
    },
    {
      "nombre": "Diana Solano",
      "direccion": "Barrio La Unión 78",
      "ciudad": "Puntarenas",
      "telefono": "+506 9999-8888"
    }
  ]
}

{'clientes': [{'nombre': 'Juan Pérez',
   'direccion': 'Calle Mayor 123',
   'ciudad': 'San José',
   'telefono': '+506 2222-3333'},
  {'nombre': 'María Gómez',
   'direccion': 'Avenida Central 456',
   'ciudad': 'Alajuela',
   'telefono': '+506 8888-4444'},
  {'nombre': 'Pedro Ramírez',
   'direccion': 'Barrio Escalante 789',
   'ciudad': 'Heredia',
   'telefono': '+506 5555-6666'},
  {'nombre': 'Ana Castro',
   'direccion': 'Avenida 10 Calle 5',
   'ciudad': 'Cartago',
   'telefono': '+506 3333-4444'},
  {'nombre': 'Carlos Jiménez',
   'direccion': 'Calle Principal 12',
   'ciudad': 'Liberia',
   'telefono': '+506 6666-7777'},
  {'nombre': 'Diana Solano',
   'direccion': 'Barrio La Unión 78',
   'ciudad': 'Puntarenas',
   'telefono': '+506 9999-8888'}]}

##

## Extraer información usando regex:
### Utilice expresiones regulares para extraer la siguiente información de cada cliente:
- Nombre completo: Juan Pérez, María Gómez, Pedro Ramírez
- Dirección completa: Calle Mayor 123, Avenida Central 456, Barrio Escalante 789
- Ciudad: San José, Alajuela, Heredia
- Número de teléfono: +506 2222-3333, +506 8888-4444, +506 5555-6666

### Imprima la información extraída para cada cliente en un formato claro y organizado.


## Pistas:

- Utilice la librería re de Python para trabajar con expresiones regulares.
- Defina patrones de expresión regular específicos para cada tipo de información que desea extraer.
- Recorra el archivo JSON y aplique los patrones regex a cada cliente.
- Utilize métodos como findall() o search() para encontrar las coincidencias en el texto.

In [21]:
import json
import re

# Cargar el archivo JSON
try:
    with open("clientes.json", "r", encoding="utf-8") as archivo:
        datos_clientes = json.load(archivo)
except FileNotFoundError as e:
    print(f"Error: El archivo JSON 'clientes.json' no se encontró.")
except json.JSONDecodeError as e:
    print(f"Error al decodificar el archivo JSON: {e}")
except Exception as e:
    print(f"Error inesperado: {e}")

# Definir patrones de regex
patron_nombre = r'"nombre": "(.*?)"'
patron_direccion = r'"direccion": "(.*?)"'
patron_ciudad = r'"ciudad": "(.*?)"'
patron_telefono = r'"telefono": "(.*?)"'

# Recorrer los datos de clientes y extraer información
for cliente in datos_clientes['clientes']:
    nombre = re.search(patron_nombre, json.dumps(cliente)).group(1)
    direccion = re.search(patron_direccion, json.dumps(cliente)).group(1)
    ciudad = re.search(patron_ciudad, json.dumps(cliente)).group(1)
    telefono = re.search(patron_telefono, json.dumps(cliente)).group(1)

    # Imprimir la información extraída
    print(f"\n**Cliente:** {nombre}")
    print(f"Dirección: {direccion}")
    print(f"Ciudad: {ciudad}")
    print(f"Teléfono: {telefono}")



**Cliente:** Juan P\u00c3\u00a9rez
Dirección: Calle Mayor 123
Ciudad: San Jos\u00c3\u00a9
Teléfono: +506 2222-3333

**Cliente:** Mar\u00c3\u00ada G\u00c3\u00b3mez
Dirección: Avenida Central 456
Ciudad: Alajuela
Teléfono: +506 8888-4444

**Cliente:** Pedro Ram\u00c3\u00adrez
Dirección: Barrio Escalante 789
Ciudad: Heredia
Teléfono: +506 5555-6666

**Cliente:** Ana Castro
Dirección: Avenida 10 Calle 5
Ciudad: Cartago
Teléfono: +506 3333-4444

**Cliente:** Carlos Jim\u00c3\u00a9nez
Dirección: Calle Principal 12
Ciudad: Liberia
Teléfono: +506 6666-7777

**Cliente:** Diana Solano
Dirección: Barrio La Uni\u00c3\u00b3n 78
Ciudad: Puntarenas
Teléfono: +506 9999-8888
